# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=b'User'))),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('content', models.CharField(default=b'', max_length=5000)),
            ],
        ),
    ]
