# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_auto_20171102_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='category',
        ),
    ]
